"use strict";

const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");
const { test } = require("node:test");

const ROOT = path.resolve(__dirname, "..");

function read(name) {
  return fs.readFileSync(path.join(ROOT, name), "utf8");
}

test("AI tutor Enter handling is wired to form submission", () => {
  const app = read("app.js");
  const html = read("index.html");
  assert.match(app, /aiTutorInput"\)\.addEventListener\("keydown", event => \{\s*if \(!shouldSubmitOnEnter\(event\)\) return;\s*event\.preventDefault\(\);\s*\$\("#aiTutorForm"\)\.requestSubmit\(\);/s);
  assert.match(html, /id="aiTutorEffort"/);
  assert.match(html, /id="aiTutorModel"/);
  assert.match(html, /id="aiTutorProvider"/);
  assert.match(app, /message,\s*providerId: practice\.tutorSettings\.providerId,\s*model: practice\.tutorSettings\.model,\s*reasoningEffort: practice\.tutorSettings\.reasoningEffort/s);
  assert.match(app, /data-ai-history-ask/);
  assert.match(app, /const available = aiOptions\.configured && target/);
  assert.match(app, /tutorHistory: \(Array\.isArray\(source\.tutorHistory\)/);
  assert.match(app, /practice\.tutorHistory\.filter\(item => item\.setId === target\.setId && item\.questionId === target\.questionId && \(!resetAt \|\| item\.askedAt > resetAt\)\)/);
  assert.match(app, /normalizeClientTutorExchange\(data\.exchange\)/);
  assert.match(html, /id="aiTutorPersistenceStatus"/);
  assert.match(html, /id="clearAiTutorButton"[^>]*>[\s\S]*清除会话/);
  assert.match(app, /function aiTutorTargetForSavedThread\(practice\)/);
  assert.match(app, /\/api\/ai\/questions\/tutor\/clear/);
  assert.match(app, /tutorResets:/);
  assert.match(app, /旧问答仍保留为学习记录/);
});

test("AI practice prepares five-question groups sequentially and continues without another generation request", () => {
  const app = read("app.js");
  const html = read("index.html");
  const css = read("styles.css");
  const server = read("server.js");
  assert.match(html, /<span>每组题数<\/span>[\s\S]*id="aiQuestionCount"/);
  assert.match(html, /<span>生成组数<\/span>[\s\S]*id="aiGroupCount"[\s\S]*value="1"[\s\S]*value="2"[\s\S]*value="3"[\s\S]*value="5"/);
  assert.match(app, /groupCount: AI_GROUP_COUNTS\.includes\(Number\(settings\.groupCount\)\)/);
  assert.match(app, /generationQueue: \(Array\.isArray\(source\.generationQueue\)/);
  assert.match(app, /groupCount: Number\(\$\("#aiGroupCount"\)\.value\) \|\| 1/);
  assert.match(app, /body: JSON\.stringify\(\{ \.\.\.settings, requestId \}\)/);
  assert.match(app, /let aiGenerationInProgress = false/);
  assert.match(app, /if \(aiGenerationInProgress\) \{[\s\S]*系统不会重复加入队列/);
  assert.match(app, /if \(!aiOptions\.configured\) \{[\s\S]*AI 尚未配置/);
  assert.match(app, /answerInput\.disabled = aiRequestInProgress/);
  assert.match(app, /previousAnswerUi && previousAnswerUi\.key === questionKey/);
  assert.match(app, /answerInput\.value = preserveAnswerUi \? previousAnswerUi\.value : question\.userAnswer \|\| ""/);
  assert.match(app, /function continuePreparedAiSet\(\)/);
  assert.match(app, /fetch\("\/api\/ai\/questions\/next"/);
  assert.match(html, /id="aiQueuePanel"/);
  assert.match(html, /id="startNextAiBatch"/);
  assert.match(app, /function renderAiQueue\(practice\)/);
  assert.match(app, /async function pollAiGenerationProgress\(\)/);
  assert.match(app, /首组 \$\{practice\.currentSet\.questions\.length\} 题已生成/);
  assert.match(app, /只重试本组/);
  assert.match(server, /activeAiGenerationJobsByUserId/);
  assert.match(server, /createAiQuestionGenerator\(config\)\.generate\(prepared\.profile, prepared\.selection\.count(?:, \{ direction: prepared\.selection\.direction \})?\)/);
  assert.doesNotMatch(server, /createAiQuestionGenerator\(config\)\.generateGroups/);
  assert.match(app, /data-queue-group-id/);
  assert.match(app, /group\.createdAt \? formatAiHistoryTime/);
  assert.match(app, /开始下一组（等待 \$\{queuedCount\} 组）/);
  assert.match(app, /generateAnotherAiSet"\)\.addEventListener\("click", continuePreparedAiSet\)/);
  assert.match(app, /startNextAiBatch"\)\.addEventListener\("click", continuePreparedAiSet\)/);
  assert.match(html, /id="clearAiQueueButton"[^>]*>[^<]*<i[^>]*trash-2[\s\S]*清空生成队列/);
  assert.match(app, /function clearAiGenerationQueue\(\)/);
  assert.match(app, /当前账号有 \$\{groupCount\} 组尚未开始的生成任务/);
  assert.match(app, /fetchWithVisibleTimeout\("\/api\/ai\/questions\/queue\/clear"/);
  assert.match(app, /已清空 \$\{Number\(data\.cancelledGroups\) \|\| 0\} 组生成任务/);
  assert.match(app, /clearAiQueueButton"\)\.addEventListener\("click"/);
  assert.match(app, /AI_GENERATION_REQUEST_TIMEOUT_MS = 15000/);
  assert.match(app, /提交结果暂不确定，再点“生成题目”会使用同一请求安全重试/);
  assert.match(server, /function clearAiGenerationQueue\(user\)/);
  assert.match(server, /item\.status = "consumed"/);
  assert.match(server, /\/api\/ai\/questions\/queue\/clear/);
  assert.doesNotMatch(app, /confirm\([^)]*覆盖[^)]*\)/);
  assert.match(css, /@media \(max-width: 520px\)[\s\S]*?\.ai-queue-item \{ grid-template-columns: 26px minmax\(0, 1fr\)/);
  assert.match(css, /@media \(max-width: 520px\)[\s\S]*?\.ai-queue-actions \{ max-width: 100%/);
  assert.match(css, /\.ai-queue-copy strong, \.ai-queue-copy span, \.ai-queue-copy small \{ overflow-wrap: anywhere; \}/);
});

test("formal review and AI practice use private whole-group review and account-bound responses", () => {
  const app = read("app.js");
  const html = read("index.html");
  const css = read("styles.css");
  assert.match(html, /id="reviewBatchReview"[\s\S]*id="gradeReviewBatch"[\s\S]*确认并批改/);
  assert.match(html, /id="reviewBatchResults"[\s\S]*id="reviewBatchResultList"/);
  assert.match(html, /id="aiBatchReview"[\s\S]*id="gradeAiBatch"[\s\S]*确认并批改/);
  assert.match(html, /id="aiBatchResults"[\s\S]*id="aiBatchResultList"/);
  assert.match(app, /function renderBatchReviewPanel\(prefix, batch\)/);
  assert.match(app, /batch-user-answer/);
  assert.match(app, /question\.answer \|\| question\.userAnswer \|\| "（未填写）"/);
  assert.match(app, /function renderBatchResultsPanel\(prefix, batch\)/);
  assert.match(app, /const resultFor = question => question\.result \|\| \(typeof question\.correct === "boolean" \? question : \{\}\)/);
  assert.match(app, /reviewBatchRequest\("\/review"/);
  assert.match(app, /reviewBatchRequest\("\/grade"/);
  assert.match(app, /reviewVariantPreparation = null;[\s\S]*?if \(activeView === "home"\) renderHome\(\)/);
  assert.match(app, /if \(API_ENABLED && currentUser && !batchMatchesSession\)[\s\S]*?answerInput\.disabled = true[\s\S]*?if \(canStartServerBatch && !startFailure\) void ensureServerReviewBatch\(session\)/);
  assert.match(app, /aiBatchRequest\("\/review"/);
  assert.match(app, /aiBatchRequest\("\/grade"/);
  assert.match(app, /const answer = \$\("#aiAnswerInput"\)\.value\.trim\(\);[\s\S]*?renderAiView\(\);[\s\S]*?nextIndex, answer/s);
  assert.match(app, /const answer = \$\("#answerInput"\)\.value\.trim\(\);[\s\S]*?renderHome\(\);[\s\S]*?nextIndex, answer/s);
  assert.match(app, /function captureAccountRequestContext\(\)/);
  assert.match(app, /if \(!accountRequestContextIsCurrent\(accountContext\)\) throw staleAccountRequestError\(\)/);
  assert.match(app, /error\.silent/);
  assert.match(app, /aiPractice: remote && remote\.aiPractice \? normalizeClientAiPractice\(remote\.aiPractice\)/);
  assert.match(app, /formalPractice: remote && remote\.formalPractice \? normalizeClientFormalPractice\(remote\.formalPractice\)/);
  assert.match(css, /@media \(max-width: 520px\)[\s\S]*?\.batch-review-panel, \.batch-results-panel, \.review-repeat-resolution \{ padding: 20px 14px 22px; \}/);
  assert.match(css, /@media \(max-width: 520px\)[\s\S]*?\.batch-result-list dl > div \{ grid-template-columns: 1fr/);
});

test("formal review batch start has bounded recovery and an explicit retry gate", () => {
  const app = read("app.js");
  const html = read("index.html");
  const css = read("styles.css");
  const serviceWorker = read("sw.js");
  const server = read("server.js");
  assert.match(html, /review-batch-client\.js\?v=77/);
  assert.match(serviceWorker, /review-batch-client\.js\?v=77/);
  assert.match(html, /id="reviewBatchStartRetryActions"[\s\S]*id="reviewBatchStartRetryButton"[\s\S]*重试保存题目快照/);
  assert.match(app, /REVIEW_BATCH_START_TIMEOUT_MS = Number\(REVIEW_BATCH_CLIENT\.DEFAULT_START_TIMEOUT_MS\) \|\| 12000/);
  assert.match(app, /REVIEW_BATCH_RECOVERY_TIMEOUT_MS = Number\(REVIEW_BATCH_CLIENT\.DEFAULT_RECOVERY_TIMEOUT_MS\) \|\| 6000/);
  assert.match(app, /startReviewBatchWithRecovery\(\{[\s\S]*batchId: session\.batchId[\s\S]*startTimeoutMs: REVIEW_BATCH_START_TIMEOUT_MS[\s\S]*recoveryTimeoutMs: REVIEW_BATCH_RECOVERY_TIMEOUT_MS/);
  assert.match(app, /function applyStartedReviewBatchAndRender\(data\)[\s\S]*applyReviewBatchResponse\(data\)[\s\S]*!batch\.questions\.length[\s\S]*reviewAnswerResetRequested = true[\s\S]*activeView === "home"\) renderHome\(\)/);
  assert.match(app, /const result = await REVIEW_BATCH_CLIENT\.startReviewBatchWithRecovery\([\s\S]*if \(!accountRequestContextIsCurrent\(accountContext\)\) throw staleAccountRequestError\(\);[\s\S]*applyStartedReviewBatchAndRender\(result\.data\)/);
  assert.match(app, /服务器已响应，但没有返回可显示的题目；请在原位置重试/);
  assert.doesNotMatch(app, /applyStartedReviewBatchAndRender\([\s\S]{0,500}(?:model\.attempts\.push|appendQuestionWordUsage|reviewBatchRequest\("\/answer")/);
  assert.match(app, /if \(reviewBatchStartFailureFor\(session\) && !manual\) return currentFormalReviewBatch\(\)/);
  assert.match(app, /if \(canStartServerBatch && !startFailure\) void ensureServerReviewBatch\(session\)/);
  assert.match(app, /const batchMatchesSession = Boolean\(formalBatch && formalBatch\.id === session\.batchId\)/);
  assert.doesNotMatch(app, /formalBatch\.id === session\.batchId && formalBatch\.date === session\.date/);
  assert.match(app, /reviewBatchStartRetryButton"\)\.addEventListener\("click", retryReviewBatchStart\)/);
  assert.match(css, /@media \(max-width: 520px\)[\s\S]*\.review-batch-start-retry \{ width: 100%/);
  assert.match(server, /FORMAL_PRACTICE_LOCK_WARN_MS/);
  assert.match(server, /JSON\.stringify\(\{ phase: "wait", operation: safeOperationName, elapsedMs: waitMs \}\)/);
  assert.match(server, /withFormalPracticeLock\(user\.id,[\s\S]*`review-batch:\$\{suffix\}`/);
});

test("AI tutor launcher supports persistent pointer dragging", () => {
  const app = read("app.js");
  const css = read("styles.css");
  assert.match(app, /function startAiTutorLaunchDrag\(event\)/);
  assert.match(app, /Math\.hypot\(event\.clientX - drag\.startX, event\.clientY - drag\.startY\) < 6/);
  assert.match(app, /localStorage\.setItem\(aiTutorLaunchPositionKey\(\)/);
  assert.match(app, /ai-tutor-launch-position-v2/);
  assert.match(app, /if \(!value \|\| typeof value !== "object" \|\| Array\.isArray\(value\)\) return null/);
  assert.match(app, /Date\.now\(\) < aiTutorLaunchSuppressClickUntil/);
  assert.match(app, /window\.addEventListener\("pointermove", moveAiTutorLaunchButton\)/);
  assert.match(app, /window\.addEventListener\("pointerup", endAiTutorLaunchDrag\)/);
  assert.match(app, /window\.addEventListener\("pointercancel", endAiTutorLaunchDrag\)/);
  assert.match(app, /window\.addEventListener\("resize", constrainAiTutorLaunchPosition\)/);
  assert.match(app, /window\.addEventListener\("orientationchange", constrainAiTutorLaunchPosition\)/);
  assert.match(css, /\.ai-tutor-launch\s*\{[^}]*cursor:\s*grab[^}]*touch-action:\s*none[^}]*user-select:\s*none/s);
});

test("exam weaknesses jump to and highlight their related wrong questions", () => {
  const app = read("app.js");
  const css = read("styles.css");
  assert.match(app, /function examWeaknessQuestionId\(exam, weakness\)/);
  assert.match(app, /data-exam-jump-question/);
  assert.match(app, /function jumpToExamQuestion\(questionId\)/);
  assert.match(app, /const scrollTop = Math\.max\(0, window\.scrollY \+ targetRect\.top - desiredTop\)/);
  assert.match(app, /window\.scrollTo\(\{ top: scrollTop, behavior: "smooth" \}\)/);
  assert.match(app, /summary !== "\[object Object\]"/);
  assert.match(css, /\.exam-question\.is-weakness-target/);
  assert.match(css, /\.exam-weakness-link/);
});

test("AI settings UI manages providers and exposes manual or automatic routing", () => {
  const app = read("app.js");
  const html = read("index.html");
  const css = read("styles.css");
  assert.match(html, /data-ai-routing-mode="manual"/);
  assert.match(html, /data-ai-routing-mode="auto"/);
  assert.match(html, /id="aiManualProvider"/);
  assert.match(html, /id="aiProviderList"/);
  assert.match(html, /id="addAiProviderButton"/);
  assert.match(app, /mode: aiConfigDraft\.mode/);
  assert.match(app, /manualProviderId: aiConfigDraft\.manualProviderId/);
  assert.match(app, /providers: aiConfigDraft\.providers\.map/);
  assert.match(app, /providerId: provider\.id/);
  assert.match(app, /const testEffort = selectedAiSettings\(\)\.reasoningEffort/);
  assert.match(app, /appliedReasoningEffort/);
  const nav = html.slice(html.indexOf('<nav class="side-nav"'), html.indexOf("</nav>"));
  const aiHeading = html.slice(html.indexOf('id="view-ai"'), html.indexOf('id="aiControls"'));
  assert.match(nav, /id="openAiConfigButton"/);
  assert.ok(nav.indexOf('data-view="records"') < nav.indexOf('id="openAiConfigButton"'), "AI settings should follow learning records in the primary nav");
  assert.doesNotMatch(aiHeading, /id="openAiConfigButton"/);
  assert.match(css, /\.ai-settings-nav-item\s*\{[^}]*margin-top:\s*0/s);
  assert.match(html, /class="ai-control-field ai-choice-control"/);
  assert.match(html, /class="ai-control-field ai-model-control"/);
  assert.match(html, /class="ai-control-field ai-effort-field"/);
  assert.match(html, /class="ai-control-field compact-control ai-question-count-control"/);
  assert.match(html, /class="ai-control-field compact-control ai-group-count-control"/);
  assert.match(css, /\.ai-controls\s*\{[^}]*grid-template-columns:\s*repeat\(6,\s*minmax\(0,\s*1fr\)\)/s);
  assert.match(css, /\.ai-effort-field\s*\{[^}]*grid-column:\s*span\s*3/s);
  assert.match(css, /@media \(max-width: 1100px\)[\s\S]*\.ai-controls\s*\{[^}]*repeat\(2,\s*minmax\(0,\s*1fr\)\)/s);
  assert.match(html, /id="aiHistoryPagination"[\s\S]*id="aiHistoryPrevPage"[\s\S]*id="aiHistoryPageStatus"[\s\S]*id="aiHistoryNextPage"/);
  assert.match(app, /const AI_HISTORY_PAGE_SIZE = 10/);
  assert.match(app, /const pageGroups = groups\.slice\(startIndex, startIndex \+ AI_HISTORY_PAGE_SIZE\)/);
  assert.match(app, /data-ai-history-details/);
  assert.match(app, /details\.addEventListener\("toggle"/);
  assert.match(app, /renderAiHistoryQuestions\(group\)/);
  assert.match(app, /aiHistoryPage <= 1/);
  assert.match(app, /aiHistoryPage >= totalPages/);
  assert.match(css, /\.ai-history-pagination\[hidden\]\s*\{[^}]*display:\s*none/s);
});

test("mistake book automatically closes mastered items while retaining a two-answer threshold", () => {
  const app = read("app.js");
  const answers = read("answer-utils.js");
  const html = read("index.html");
  const server = read("server.js");
  assert.match(answers, /const MISTAKE_AUTO_RESOLVE_STREAK = 2/);
  assert.match(answers, /function mistakeCorrectStreak\(attempts, taskId\)/);
  assert.match(answers, /attempt\.gradingStatus !== "partial"/);
  assert.match(answers, /function mistakeIsResolved\(attempts, taskId\)/);
  assert.match(server, /\.filter\(item => !mistakeIsResolved\(next\.attempts, item && item\.taskId\)\)/);
  assert.match(app, /mistakeIsResolved\(model\.attempts, row\.taskId\)/);
  assert.match(app, /连续答对 \$\{row\.correctStreak\}\/\$\{MISTAKE_AUTO_RESOLVE_STREAK\}/);
  assert.match(html, /连续 2 次完全答对后自动销号/);
});

test("exam UI uses dedicated APIs, optional listening, and whole-paper submission", () => {
  const app = read("app.js");
  const html = read("index.html");
  assert.match(html, /data-view="exam"/);
  assert.match(html, /id="examIncludeEssay"/);
  assert.match(html, /id="examIncludeListening"/);
  assert.match(html, /data-exam-points="100"/);
  assert.match(html, /data-exam-points="150"/);
  assert.match(app, /speechSynthesisAvailable/);
  assert.match(app, /utterance\.rate = 0\.75/);
  assert.match(app, /\/api\/ai\/exams\/listening/);
  assert.match(app, /\/api\/ai\/exams\/current/);
  assert.match(app, /\/api\/ai\/exams\/submit/);
  assert.match(app, /EXAM_GENERATION_POLL_MS/);
  assert.match(app, /monitorExamGeneration\(examState\.generation\.id\)/);
  assert.match(app, /generation\.status === "failed"/);
  assert.match(app, /"X-English-Review-Exam-Version": EXAM_GENERATION_API_VERSION/);
  assert.match(app, /\[504, 524\]\.includes\(response\.status\)/);
  assert.match(app, /exam\.questions\.find\(question => !examAnswerComplete/);
  assert.match(app, /完形填空材料/);
  assert.match(app, /exam\.clozePassage/);
  assert.match(app, /材料题材料/);
});

test("ability, dictation, and focused practice UI share speech and evidence controls", () => {
  const app = read("app.js");
  const html = read("index.html");
  assert.match(html, /data-view="abilities"/);
  assert.match(html, /id="abilityRadar"/);
  assert.match(app, /\/api\/abilities/);
  assert.match(html, /data-view="dictation"/);
  assert.match(app, /\/api\/ai\/dictation\/speech/);
  assert.match(app, /\/api\/ai\/dictation\/submit/);
  assert.match(html, /data-view="focused"/);
  assert.match(app, /\/api\/ai\/focused\/submit/);
  assert.match(app, /Array\.from\(\{ length: 5 \}/);
  assert.match(app, /speechButtonHtml/);
  assert.match(app, /question\.direction === "en-zh" \? speechButtonHtml/);
});

test("pronunciation lesson lists and filters reference sounds without pretending word speech is isolated IPA", () => {
  const app = read("app.js");
  const html = read("index.html");
  const serviceWorker = read("sw.js");

  assert.match(html, /data-view="pronunciation"/);
  assert.match(html, /id="pronunciationConcepts"/);
  assert.match(html, /data-pronunciation-filter="learned"/);
  assert.match(html, /data-pronunciation-filter="vowel"/);
  assert.match(html, /data-pronunciation-filter="consonant"/);
  assert.match(html, /data-pronunciation-filter="all"/);
  assert.match(html, /pronunciation-data\.js\?v=77/);
  assert.match(app, /function renderPronunciation\(\)/);
  assert.match(app, /item\.learned === true/);
  assert.match(app, /phonemeSoundButtonHtml\(item\)/);
  assert.match(app, /speechButtonHtml\(item\.example, `慢速播放完整示范词/);
  assert.match(app, /data-pronunciation-sound/);
  assert.match(app, /中文辅助/);
  assert.match(serviceWorker, /pronunciation-data\.js\?v=77/);
});

test("daily preview loads the latest synced document and renders bounded Markdown safely", () => {
  const app = read("app.js");
  const html = read("index.html");
  const css = read("styles.css");
  const sync = read("scripts/sync-learning-profile.ps1");
  assert.match(html, /data-view="preview"/);
  assert.match(html, /id="previewHistorySelect"/);
  assert.match(html, /id="refreshPreviewButton"/);
  assert.match(app, /fetch\("\/api\/preview", \{ cache: "no-store", credentials: "same-origin" \}\)/);
  assert.match(app, /function previewMarkdownHtml\(value\)/);
  assert.match(app, /escapeHtml\(code\.join\("\\n"\)\)/);
  assert.match(app, /previewState\.previews/);
  assert.doesNotMatch(app, /documents\.map\(document\s*=>\s*\{\s*const option = document\.createElement/);
  assert.match(css, /\.preview-table-wrap\s*\{[^}]*overflow-x:\s*auto/s);
  assert.match(sync, /Select-Object -First 30/);
  assert.match(sync, /previews = \$previewDocuments/);
  assert.match(sync, /网站课程内容\.json/);
  assert.match(sync, /\/api\/content\/batch/);
  assert.match(sync, /notesAdded/);
  assert.match(sync, /\[string\]\$StatusPath/);
  assert.match(sync, /function Invoke-SyncRequest/);
  assert.match(sync, /MaximumAttempts = 3/);
  assert.match(sync, /downloadSuccess/);
  assert.match(sync, /下载网站档案仍会继续/);
  assert.match(sync, /function Invoke-NodeSyncRequest/);
  assert.match(sync, /sync-http-request\.js/);
  assert.match(sync, /compatibilityTransportUsed/);
  assert.doesNotMatch(sync, /-ArgumentList[^\n]*(SyncToken|WriteToken)/);
});

test("today review removes preview words from new, cached, library, and mistake entry paths", () => {
  const app = read("app.js");
  assert.match(app, /function reviewTaskIsEligible\(task, studyDate = localDate\(\)\)/);
  assert.match(app, /isReviewEligibleItem\(task\.item, DATA\.currentDay, studyDate\)/);
  assert.match(app, /function pruneReviewSession\(session\)/);
  assert.match(app, /let changed = pruneReviewSession\(session\)/);
  assert.match(app, /buildMistakePracticeQueue[\s\S]*\.filter\(candidate => reviewTaskIsEligible\(taskById\.get\(candidate\)\)\)/);
  assert.match(app, /item\.preview \? '<span class="type-badge">预习<\/span>'/);
});

test("library paginates filtered English and Chinese results with continuous sequence numbers", () => {
  const app = read("app.js");
  const html = read("index.html");
  const css = read("styles.css");
  const serviceWorker = read("sw.js");
  const libraryUsage = read("library-usage.js");
  assert.match(html, /id="librarySearch"[^>]*aria-label="搜索英文或中文"/);
  assert.match(html, /id="libraryPageSize"[\s\S]*value="10" selected[\s\S]*value="20"[\s\S]*value="50"[\s\S]*value="100"/);
  assert.match(html, /id="libraryPrevPage"/);
  assert.match(html, /id="libraryNextPage"/);
  assert.match(app, /class=\\"sequence-cell\\">序号/);
  assert.match(app, /normalizeChinese\(item\.chinese\)\.includes\(searchChinese\)/);
  assert.match(app, /normalizeEnglish\(item\.english\)\.includes\(searchEnglish\)/);
  assert.match(html, /library-usage\.js\?v=77/);
  assert.match(serviceWorker, /library-usage\.js\?v=77/);
  assert.match(app, /LIBRARY_USAGE\.sortItems\(matchingItems, libraryUsageRows, libraryUsageSort, libraryUsageOrder\)/);
  assert.match(libraryUsage, /Planned\/preview words do not have formal usage rows/);
  assert.match(app, /filteredItems\.slice\(startIndex, startIndex \+ pageSize\)/);
  assert.match(app, /items\.map\(\(item, index\) =>/);
  assert.match(app, /class="sequence-cell">\$\{startIndex \+ index \+ 1\}/);
  assert.match(app, /libraryPage = 1; renderLibrary\(\)/);
  assert.match(app, /libraryPage = Math\.max\(1, libraryPage - 1\)/);
  assert.match(app, /libraryPage \+= 1/);
  assert.match(css, /\.data-table \.sequence-cell\s*\{[^}]*text-align:\s*center/s);
  assert.match(css, /\.library-pagination\s*\{[^}]*display:\s*flex/s);
});

test("completed learning invalidates word usage rows without crossing account state", () => {
  const app = read("app.js");
  const usage = read("library-usage.js");
  assert.match(app, /function mergeServerModel\(remote\)[\s\S]*wordUsageRevision\(merged\.wordUsage\) !== previousRevision\)[\s\S]*invalidateLibraryUsage\(\)/);
  assert.match(app, /function setAccountContext\(user\)[\s\S]*resetLibraryUsageCache\(\)/);
  assert.match(app, /requestUserId = String\(currentUser\.id \|\| ""\)[\s\S]*String\(currentUser\.id \|\| ""\) !== requestUserId/);
  assert.match(app, /window\.addEventListener\("focus", refreshVisibleLibraryUsage\)/);
  assert.match(app, /async function gradeAiBatch\(\)[\s\S]*invalidateLibraryUsage\(\)/);
  assert.match(app, /async function submitDictation\(event\)[\s\S]*invalidateLibraryUsage\(\)/);
  assert.match(app, /async function submitFocusedPractice\(event\)[\s\S]*invalidateLibraryUsage\(\)/);
  assert.match(app, /async function submitExam\(event\)[\s\S]*invalidateLibraryUsage\(\)/);
  assert.match(app, /if \(path === "\/submit"\) invalidateLibraryUsage\(\)/);
  assert.match(app, /LIBRARY_USAGE\.describeRow\(usage, libraryUsageFrom, libraryUsageTo\)/);
  assert.match(app, /usageDescription\?\.period/);
  assert.match(app, /行内所选区间：\$\{usageScope\.label\}/);
  assert.match(app, /行内对\/错\/提示\/正确率：全部日期累计/);
  assert.match(app, /libraryUsageRows = new Map\(\);\s*libraryPage = 1;\s*void loadLibraryUsage\(true\)/);
  assert.match(usage, /所选区间 \$\{Math\.max\(0, Number\(row\.periodUsage\) \|\| 0\)\} 次/);
  assert.match(usage, /const prefix = scope\.active \? "区间" : "累计"/);
});

test("preview words have a next-day-only page with speech and learned-feature isolation", () => {
  const app = read("app.js");
  const html = read("index.html");
  const css = read("styles.css");
  const server = read("server.js");
  assert.match(html, /data-view="preview-words"/);
  assert.match(html, /id="previewWordsGrid"/);
  assert.match(html, /id="refreshPreviewWordsButton"/);
  assert.match(app, /fetch\("\/api\/preview\/words", \{ cache: "no-store", credentials: "same-origin" \}\)/);
  assert.match(app, /function normalizePreviewWordsResponse\(value\)/);
  assert.match(app, /item => item && item\.day === nextDay/);
  assert.match(app, /function renderMaskedPreviewWordCards\(words\)/);
  assert.match(app, /speechButtonHtml\(item\.english, "慢速播放预习单词 " \+ item\.english\)/);
  assert.match(app, /data-preview-reveal-id/);
  assert.match(html, /data-preview-mask-mode="hide-chinese"/);
  assert.match(html, /data-preview-mask-mode="hide-english"/);
  assert.match(app, /const learnedItems = allItems\.filter\(item => !item\.preview\)/);
  assert.match(css, /\.preview-words-grid\s*\{[^}]*grid-template-columns:/s);
  assert.match(server, /url\.pathname === "\/api\/preview\/words"/);
  assert.match(server, /content\.words\.filter\(item => !item\.preview && item\.learned/);
});

test("preview practice keeps word and sentence exercises isolated from formal review", () => {
  const app = read("app.js");
  const html = read("index.html");
  const server = read("server.js");
  const previewPractice = read("server/preview-practice.js");
  const answerUtils = read("answer-utils.js");
  const reviewVariants = read("review-variants.js");
  assert.match(html, /data-view="preview-practice"/);
  assert.match(html, /id="previewPracticeForm"/);
  assert.match(html, /data-preview-practice-mode="word"/);
  assert.match(html, /data-preview-practice-mode="sentence"/);
  assert.match(app, /function previewPracticeWords\(\)/);
  assert.match(app, /function previewPracticeGrade\(task, answer\)/);
  assert.match(app, /function clientPreviewAcceptedChinese\(english, chinese, acceptedChinese = \[\]\)/);
  assert.match(app, /REVIEW_VARIANTS\.expandRegisteredChineseAnswers\(DATA, english, answers, 16\)/);
  assert.match(app, /acceptedChinese: clientPreviewAcceptedChinese\(sentence\.english, chinese, \[sourceChinese,/);
  assert.match(app, /你的答案使用了正式词库登记的中文同义词/);
  assert.match(app, /chineseNaturalDeepMatches\(answer, task\.acceptedChinese/);
  assert.match(answerUtils, /const NATURAL_DEEP_EXPLANATION =/);
  assert.match(reviewVariants, /const DEEP_DEGREE_BOUNDARY_WORDS = new Set/);
  assert.match(reviewVariants, /naturalizePlainDeepChinese/);
  assert.match(server, /normalizeStoredContentSentences/);
  assert.match(previewPractice, /NATURAL_DEEP_EXPLANATION/);
  assert.match(app, /function currentPreviewPracticeTask\(state = ensurePreviewPracticeState\(\)\)/);
  assert.match(app, /const state = ensurePreviewPracticeState\(\);\s*const task = currentPreviewPracticeTask\(state\);/s);
  assert.match(app, /Object\.assign\(stored, current\);\s*model\.previewPractice = stored;\s*return stored;/s);
  assert.match(app, /const targetState = ensurePreviewPracticeState\(\);\s*if \(targetState\.key !== key\) return;/s);
  assert.match(app, /previewPracticeSentencePreparation\?\.promise === promise/);
  assert.match(app, /showPreviewPracticeFormError\("请先输入答案"\)/);
  assert.match(app, /previewPracticeInput"\)\.addEventListener\("input", clearPreviewPracticeFormError\)/);
  assert.match(app, /function handlePreviewPracticeEnter\(event\)/);
  assert.match(app, /input\.readOnly = Boolean\(result\)/);
  assert.match(app, /previewPracticeInput"\)\.addEventListener\("keydown", handlePreviewPracticeEnter\)/);
  assert.match(app, /previewPracticeNext"\)\.addEventListener\("keydown", handlePreviewPracticeEnter\)/);
  assert.match(app, /const focusTarget = result \? \$\("#previewPracticeNext"\) : \$\("#previewPracticeInput"\)/);
  assert.match(html, /id="previewPracticeInput"[^>]*aria-describedby="previewPracticeFeedback"/);
  assert.match(html, /id="previewPracticeFeedback"[^>]*role="status"[^>]*aria-live="polite"/);
  assert.match(app, /\/api\/preview\/practice\/sentences/);
  assert.match(app, /previewPracticeStatusMessage = .*每 5 分钟自动重试/s);
  assert.match(app, /句子题必须包含预习词，也会组合已学词帮助记忆/);
  assert.match(app, /model\.previewPractice/);
  assert.match(app, /previewPracticeTasksForMode/);
  assert.match(html, /id="previewPracticeAgain"[\s\S]*>[^<]*再练一轮/);
  assert.match(app, /function resetPreviewPracticeRound\(\)/);
  assert.match(app, /state\.answers = \{\};\s*state\.results = \{\};\s*state\.pending = \{\};/s);
  assert.match(app, /继续使用当前这批预习词句/);
  assert.match(app, /previewPracticeAgain"\)\.addEventListener\("click", resetPreviewPracticeRound\)/);
  assert.match(html, /id="previewPracticeHistoryList"/);
  assert.match(app, /function renderPreviewPracticeHistory\(\)/);
  assert.match(app, /function recordPreviewPracticeHistory\(state\)/);
  assert.match(app, /model\.previewPracticeHistory/);
  assert.match(app, /detailedExplanation: String\(result\.detailedExplanation/);
  assert.match(server, /handlePreviewPracticeSentences/);
  assert.match(server, /const learnedWords = \[\.\.\.profile\.allowedWords\]/);
  assert.match(server, /previewWordTokens = previewWords\.map/);
  assert.match(server, /\[\.\.\.learnedWords, \.\.\.previewWords\.flatMap/);
  assert.match(server, /targetTokens\.every\(token => tokens\.includes\(token\)\)/);
  assert.match(server, /expandPreviewAcceptedChinese\(contentValue, english/);
  assert.match(server, /expandPreviewAcceptedChinese\(previewContentForAccount\(previewData\), english/);
  assert.match(previewPractice, /repairRegisteredChineseResults/);
  assert.match(previewPractice, /不会计入正式错题、待复习、薄弱点或能力分/);
  assert.match(server, /url\.pathname === "\/api\/preview\/practice\/sentences"/);
  assert.doesNotMatch(app, /model\.attempts\.push\([^)]*previewPractice/s);
});

test("preview sentence documentation states the learned-word and retry rules", () => {
  const api = read("API.md");
  const usage = read("使用说明.md");
  assert.match(api, /POST \| `\/api\/preview\/practice\/sentences`/);
  assert.match(api, /可以组合已经正式学过的单词/);
  assert.match(api, /retryAfterMs: 300000/);
  assert.match(usage, /每句都必须带上对应的预习词，同时可以把已经学过的老单词放进句子里/);
});

test("review sentence variants run in the background, repair partial failures, and retry after five minutes", () => {
  const app = read("app.js");
  const html = read("index.html");
  const css = read("styles.css");
  const server = read("server.js");
  const aiGrader = read("server/ai-grader.js");
  assert.match(app, /const REVIEW_VARIANT_RETRY_MS = 5 \* 60 \* 1000/);
  assert.match(app, /const REVIEW_VARIANT_POLL_MS = 2000/);
  assert.match(app, /const REVIEW_VARIANT_WAIT_TIMEOUT_MS = 12 \* 60 \* 1000/);
  assert.match(app, /const REVIEW_VARIANT_START_REQUEST_TIMEOUT_MS = 15000/);
  assert.match(app, /const REVIEW_VARIANT_POLL_REQUEST_TIMEOUT_MS = 15000/);
  assert.match(app, /function scheduleReviewVariantRetry\(session, key\)/);
  assert.match(app, /async function waitForReviewVariantJob\(data, key\)/);
  assert.match(app, /sentence-variants\?jobId=/);
  assert.match(html, /id="reviewVariantRetryButton"/);
  assert.match(app, /async function retryReviewSentenceVariants\(\)/);
  assert.match(app, /prepareReviewSentenceVariants\(session, true\)/);
  assert.match(app, /reviewVariantRetryButton.*retryReviewSentenceVariants/s);
  assert.match(app, /model: settings\.model, reasoningEffort: settings\.reasoningEffort, force: Boolean\(force\)/);
  assert.match(app, /signal: requestController\.signal/);
  assert.match(app, /读取本轮句子池超时，请点击立即重试/);
  const preparationSource = app.slice(app.indexOf("async function prepareReviewSentenceVariants"), app.indexOf("async function retryReviewSentenceVariants"));
  assert.doesNotMatch(preparationSource, /!aiOptionsLoaded|!aiOptions\.configured/, "saved pool lookup must run before AI availability matters");
  assert.match(app, /reviewVariantRetryUi\(session, Boolean\(missingSentenceCount\)\)/, "later missing sentence tasks must expose the group retry action");
  assert.match(app, /if \(!session \|\| !reviewSentencePreparationState\(session\)\.shouldRequest\) return;/, "manual retry must cover every missing sentence in the group");
  assert.match(app, /function activeReviewVariantSession\(key\)/);
  assert.match(app, /targetSession = activeReviewVariantSession\(key\)[\s\S]*applyReviewVariantResults\(targetSession, targetMissing, data\)/, "a response must update the current merged session rather than a stale object");
  assert.match(server, /if \(body\.prefetch !== true\) \{[\s\S]*assignReviewVariantPoolTasks\(pool, tasks, content\)/, "force retries must still reuse the persisted pool first");
  assert.match(css, /\.review-variant-retry\s*\{/);
  assert.match(app, /AI 暂不可用，将每 5 分钟自动重试/);
  assert.match(app, /if \(data\.source !== "ai"\)/);
  assert.match(server, /const AI_SENTENCE_RETRY_MS = 5 \* 60 \* 1000/);
  assert.match(server, /const REVIEW_VARIANT_MAX_REPAIR_ROUNDS = 3/);
  assert.match(server, /const REVIEW_VARIANT_UPSTREAM_TIMEOUT_MS = 10 \* 60 \* 1000/);
  assert.match(server, /function failReviewVariantJob\(job, error\)/);
  assert.match(server, /REVIEW_VARIANT_TIMEOUT/);
  assert.match(server, /generateReviewVariantsWithRepairs/);
  assert.match(server, /validateReviewVariantCandidate/);
  assert.match(server, /pending = failures\.map/);
  assert.match(server, /status: remainingFailures\.length \? "needs-attention" : "completed"/);
  assert.match(app, /if \(data\.autoRetry === false\) cancelReviewVariantRetry\(key\)/);
  assert.match(server, /status: "pending", jobId: job\.id/);
  assert.match(server, /AI 变式暂时不可用，将每 5 分钟自动重试/);
  assert.match(server, /const requestedEffort = AI_EFFORTS\.includes\(body\.reasoningEffort\)/);
  assert.doesNotMatch(server, /const route = selectAiCandidates\(aiSettings, \{ model: requestedModel, reasoningEffort: "low" \}\)/);
  assert.match(server, /连续 3 轮未通过校验/);
  assert.match(server, /reasonCode: failure\.reasonCode/);
  assert.match(aiGrader, /disableTimeout: true/);
  assert.doesNotMatch(server, /using local fallback/);
  assert.doesNotMatch(app, /已使用本地自然变式/);
});

test("daily sentence pools persist fifty variants and client merges cannot erase them", () => {
  const app = read("app.js");
  const html = read("index.html");
  const server = read("server.js");
  const pool = read("server/review-variant-pool.js");
  assert.match(app, /function mergeReviewSessions\(localSession, remoteSession\)/);
  assert.match(app, /remote\.variants[\s\S]*local\.variants/);
  assert.match(app, /prefetch:\s*true/);
  assert.match(app, /reviewVariantPoolStatus/);
  assert.match(app, /function clearReviewVariantPoolStatusPolling\(\)/);
  assert.match(app, /function scheduleReviewVariantPoolStatusPolling\(\)/);
  assert.match(app, /fetch\("\/api\/state", \{ cache: "no-store", credentials: "same-origin" \}\)/);
  assert.match(app, /function updateReviewVariantPoolStatus\(value, render = false\)/);
  assert.match(html, /id="reviewVariantPoolStatus"/);
  assert.match(html, /id="reviewVariantPoolStatusCard"/);
  assert.match(html, /id="reviewVariantPoolCount"/);
  assert.match(html, /id="reviewVariantPoolProgress"/);
  assert.match(pool, /const REVIEW_VARIANT_POOL_TARGET = 50/);
  assert.match(pool, /const REVIEW_VARIANT_POOL_BATCH = 20/);
  assert.match(pool, /const compatible = pool\.variants\.filter/);
  assert.match(pool, /const candidates = compatible\.length \? compatible : pool\.variants/);
  assert.match(pool, /remainingCount/);
  assert.match(server, /function mergeClientWritableState\(existingValue, bodyValue\)/);
  assert.match(server, /const next = \{ \.\.\.existing \}/);
  assert.match(server, /startReviewVariantPoolFill/);
  assert.match(server, /prepareReviewVariantPoolsAfterCourseSync/);
  assert.match(server, /previousSyncKey !== currentSyncKey/);
  assert.match(pool, /syncCycleChanged/);
  assert.doesNotMatch(pool, /normalized\.date !== expectedDate/);
  assert.match(html, /本轮 AI 句子池/);
  assert.match(server, /function findStoredPoolSentenceTask\(user, taskId, variantId = ""\)/);
  assert.match(server, /accepted only when the server has assigned that exact/);
});

test("remote state saves are narrow, serialized, and skip server-authoritative response echoes", () => {
  const app = read("app.js");
  const html = read("index.html");
  const serviceWorker = read("sw.js");
  const server = read("server.js");
  const stateSync = read("state-sync-client.js");
  assert.match(html, /state-sync-client\.js\?v=77/);
  assert.match(serviceWorker, /state-sync-client\.js\?v=77/);
  assert.match(app, /STATE_SYNC\.createStateSaveQueue/);
  assert.match(app, /remoteStateQueue\.scheduleState\(model/);
  assert.match(app, /remoteStateQueue\?\.markServerState\(remote\)/);
  assert.match(app, /function applyReviewBatchResponse[\s\S]*?saveModel\(\{ remote: false \}\)/);
  assert.match(app, /function applyAiPracticeResponse[\s\S]*?saveModel\(\{ remote: false \}\)/);
  assert.match(app, /remoteStateQueue\.scheduleStudyTime\(state, \{ immediate: true \}\)/);
  assert.match(stateSync, /function clientStateProjection\(value\)/);
  assert.match(stateSync, /if \(inFlight\) \{[\s\S]*const result = await inFlight\.promise;[\s\S]*return pending \? \(await flush\(\)\) \|\| result : result;/);
  assert.match(stateSync, /const url = record\.kind === "study-time" \? "\/api\/state\/study-time" : "\/api\/state"/);
  assert.doesNotMatch(stateSync, /aiPractice|formalPractice|aiExam/);
  assert.match(server, /function handleStudyTimeState\(req, res, user\)/);
  assert.match(server, /publicFormalEvidenceState\(applied\.state\)/);
});

test("sentence pool viewer exposes searchable paginated read-only sentences and the current assignment", () => {
  const app = read("app.js");
  const html = read("index.html");
  const css = read("styles.css");
  assert.match(html, /id="reviewVariantPoolToggle"[^>]*aria-controls="reviewVariantPoolBrowser"/);
  assert.match(html, /id="reviewVariantPoolSearch"[^>]*placeholder="搜索英文或中文"/);
  assert.match(html, /id="reviewVariantPoolPageSize"[\s\S]*value="10" selected[\s\S]*value="20"[\s\S]*value="50"/);
  assert.match(html, /id="reviewVariantPoolShowChinese"[^>]*type="checkbox"/);
  assert.match(html, /id="reviewVariantPoolList"/);
  assert.match(html, /id="reviewVariantPoolPrevPage"/);
  assert.match(html, /id="reviewVariantPoolNextPage"/);
  assert.match(html, /id="reviewVariantStatsFrom"[^>]*type="date"/);
  assert.match(html, /id="reviewVariantStatsTo"[^>]*type="date"/);
  assert.match(html, /id="reviewVariantStatsSort"[\s\S]*value="attempts"[\s\S]*value="correct"[\s\S]*value="wrong"[\s\S]*value="accuracy"[\s\S]*value="recent"/);
  assert.match(html, /id="reviewVariantStatsClear"[\s\S]*全部日期/);
  assert.match(app, /Array\.isArray\(value\.sentences\)[\s\S]*\.slice\(0, 50\)/);
  assert.match(app, /normalizeEnglish\(item\.english\)\.includes\(englishQuery\)/);
  assert.match(app, /normalizeChinese\(item\.chinese\)\.includes\(chineseQuery\)/);
  assert.match(app, /filtered\.slice\(start, start \+ reviewVariantPoolPageSize\)/);
  assert.match(app, /currentVariantId \? item\.id === currentVariantId/);
  assert.match(app, /class="review-pool-current">当前复习/);
  assert.match(app, /reviewVariantPoolShowChinese \? `<p class="review-pool-chinese"/);
  assert.match(app, /开始日期不能晚于结束日期/);
  assert.match(app, /reviewVariantStatsFrom = "";[\s\S]*reviewVariantStatsTo = "";/);
  assert.match(app, /做 \$\{stats\.attempts\}[\s\S]*对 \$\{stats\.correct\}[\s\S]*错 \$\{stats\.wrong\}/);
  assert.match(css, /\.review-pool-item\.is-current/);
  assert.match(css, /\.review-pool-english[^}]*overflow-wrap:\s*anywhere/s);
  assert.match(css, /@media \(max-width: 520px\)[\s\S]*\.review-pool-item\s*\{[^}]*grid-template-columns:\s*30px minmax\(0, 1fr\)/s);
  assert.match(css, /@media \(max-width: 520px\)[\s\S]*?\.review-pool-stats-controls \{[^}]*grid-template-columns: repeat\(2, minmax\(0, 1fr\)\)/s);

  const handlerStart = app.indexOf('$("#reviewVariantPoolToggle").addEventListener');
  const handlerEnd = app.indexOf('$$("[data-library-type]")', handlerStart);
  const handlers = app.slice(handlerStart, handlerEnd);
  assert.ok(handlerStart >= 0 && handlerEnd > handlerStart);
  assert.doesNotMatch(handlers, /fetch\(|saveModel\(|scheduleRemoteSave\(|syncRemoteState\(/);
  const currentRender = app.slice(app.indexOf("function renderCurrentReviewVariantPoolBrowser"), app.indexOf("function renderReviewVariantPoolStatus"));
  assert.doesNotMatch(currentRender, /getSession\(|saveModel\(|fetch\(/);
});

test("review redraws preserve local input and restore server-saved group drafts", () => {
  const app = read("app.js");
  assert.match(app, /let reviewAnswerResetRequested = true/);
  assert.match(app, /dataset\.reviewTaskKey/);
  assert.match(app, /const previousReviewUi = answerInput \? \{/);
  assert.match(app, /const preserveReviewUi = !resetAnswer && previousReviewUi && previousReviewUi\.taskKey === taskKey/);
  assert.match(app, /answerInput\.value = preserveReviewUi[\s\S]*?immediateMode[\s\S]*?immediateCorrect[\s\S]*?draftQuestion\.answer[\s\S]*?: \(draftQuestion \? draftQuestion\.answer : ""\)/);
  assert.match(app, /const taskKey = `\$\{task\.taskId\}[\s\S]*?draftQuestion\?\.attemptRequestId/);
  assert.match(app, /reviewBatchRequest\("\/draft"/);
  assert.match(app, /body: \{\s*batchId: batch\.id,\s*questionId: question\.id/s);
  assert.match(app, /function advance\(retry = false\) \{\s*reviewAnswerResetRequested = true/);
  assert.match(app, /function replaceReviewSession\(taskIds, mode = "all", \{ allowRepeat = false \} = \{\}\) \{\s*reviewAnswerResetRequested = true/);
});

test("completed review groups retire client state and legacy repeats require bounded explicit recovery", () => {
  const app = read("app.js");
  const html = read("index.html");
  const css = read("styles.css");
  assert.match(app, /function projectReviewBatchToSession\(batch\)/);
  assert.match(app, /REVIEW_SESSION\.applyReviewBatchToSession\(current, batch\)/);
  assert.match(app, /function applyRetiredReviewBatchResponse\(data\)/);
  assert.match(app, /REVIEW_SESSION\.retireReviewSession/);
  assert.match(app, /reviewBatchRequest\("\/archive", \{ body: \{ batchId: batch\.id \} \}\)/);
  assert.match(app, /function startNextReviewGroup\(\)[\s\S]*buildGuidedReviewBatch\(DAILY_TARGET\)[\s\S]*replaceReviewSession/);
  assert.match(app, /allowRepeat: session\.allowRepeat === true/);
  assert.match(app, /replaceReviewSession\(\[taskId\], reviewMode, \{ allowRepeat: true \}\)/);
  assert.match(app, /resolveRepeatedReviewBatchWithRecovery\(\{/);
  assert.match(app, /resolveTimeoutMs: REVIEW_REPEAT_RESOLVE_TIMEOUT_MS/);
  assert.match(app, /recoveryTimeoutMs: REVIEW_REPEAT_RECOVERY_TIMEOUT_MS/);
  assert.match(app, /if \(action === "discard" && !currentFormalReviewBatch\(\)\) startNextReviewGroup\(\)/);
  assert.match(app, /confirmDiscard: action === "discard" && !automatic/);
  assert.match(app, /if \(!key \|\| reviewRepeatAutoAttemptKey === key\) return/);
  assert.match(app, /queueMicrotask\(\(\) => \{ void resolveRepeatedReviewBatch\("discard", \{ automatic: true, expectedBatchId: batch\.id, expectedKind: repeated\.kind \}\); \}\)/);
  assert.match(app, /stable app root so a replaced button cannot lose its action handler/);
  assert.match(app, /event\.target\.closest\("#continueRepeatedReviewBatch, #discardRepeatedReviewBatch"\)/);
  assert.match(app, /expectedBatchId: panel && panel\.dataset\.reviewBatchId/);
  assert.match(app, /expectedKind: panel && panel\.dataset\.reviewRepeatKind/);
  assert.match(app, /automatic \? "" : action === "continue" \? "draft" : "empty"/);
  assert.match(app, /if \(!automatic\) renderHome\(\)/);
  assert.doesNotMatch(app, /\$\("#discardRepeatedReviewBatch"\)\.addEventListener\("click"/);
  assert.match(html, /id="reviewRepeatResolution"[\s\S]*id="continueRepeatedReviewBatch"[\s\S]*id="discardRepeatedReviewBatch"/);
  assert.match(css, /@media \(max-width: 520px\)[\s\S]*\.review-repeat-resolution-actions \{ display: grid; grid-template-columns: 1fr; \}/);
});

test("partial answers have distinct feedback and preserve mastery", () => {
  const app = read("app.js");
  const css = read("styles.css");
  const server = read("server.js");
  const formalPractice = read("server/formal-practice.js");
  assert.match(app, /gradingStatus === "partial"/);
  assert.match(app, /基本理解正确/);
  assert.match(app, /state\.level = Math\.max\(1, Number\(state\.level\) \|\| 0\)/);
  assert.match(server, /next\.level = Math\.max\(1, Number\(previous\.level\) \|\| 0\)/);
  assert.match(app, /function aiQuestionScore\(question\)/);
  assert.match(app, /\$\{batch\.questions\.length\} 题 · \$\{correctCount\} 题完全正确 · \$\{formatQuestionScore\(earned\)\} \/ \$\{batch\.questions\.length\} 分/);
  assert.match(app, /部分正确" : result\.correct \? "正确" : "错误"/);
  assert.match(formalPractice, /const score = Number\.isFinite\(scoreValue\) \? Math\.max\(0, Math\.min\(1, scoreValue\)\)/);
  assert.match(server, /result\.gradingStatus === "partial"[\s\S]*?next\.nextDue = addStudyDays\(studyDate, 1\)/);
  assert.match(css, /\.feedback\.is-partial/);
});

test("exam UI supports A3 pages, printing, draft recovery, and paper-photo grading", () => {
  const app = read("app.js");
  const html = read("index.html");
  const css = read("styles.css");
  assert.match(html, /id="printExamButton"/);
  assert.match(html, /id="examPhotoInput"[^>]*multiple/);
  assert.match(app, /window\.print\(\)/);
  assert.match(app, /compressExamPhoto/);
  assert.match(app, /\/api\/ai\/exams\/photo-grade/);
  assert.match(app, /class="exam-page"/);
  assert.match(css, /aspect-ratio:\s*420\s*\/\s*297/);
  assert.match(css, /@page\s*\{\s*size:\s*A3 landscape/);
  assert.match(css, /\.exam-page-content\s*\{[^}]*column-count:\s*2/s);
});

test("PWA client assets consistently use the displayed cache version 77", () => {
  const index = read("index.html");
  const app = read("app.js");
  const serviceWorker = read("sw.js");
  const versionedSources = `${index}\n${app}\n${serviceWorker}`;
  const versions = Array.from(versionedSources.matchAll(/\?v=(\d+)/g), match => match[1]);
  const displayedVersion = index.match(/id="appVersionBadge"[^>]*>v(\d+)<\/span>/);

  assert.ok(displayedVersion, "the current version should be visible in the page header");
  assert.ok(versions.length > 0);
  assert.deepEqual(new Set(versions), new Set([displayedVersion[1]]));
  assert.equal(displayedVersion[1], "77");
  assert.match(serviceWorker, /const CACHE_NAME = "daily-english-review-v77"/);
});

test("PWA cached reloads do not wait on every static network request", () => {
  const app = read("app.js");
  const serviceWorker = read("sw.js");
  const server = read("server.js");
  assert.match(server, /const STATIC_ASSET_VERSION = "77"/);
  assert.match(server, /public, max-age=31536000, immutable/);
  assert.match(server, /res\.setHeader\("ETag", entityTag\)/);
  assert.match(server, /res\.setHeader\("Last-Modified", stats\.mtime\.toUTCString\(\)\)/);
  assert.match(server, /staticRequestIsFresh\(req, stats, entityTag\)/);
  assert.match(serviceWorker, /const NAVIGATION_NETWORK_TIMEOUT_MS = 2500/);
  assert.match(serviceWorker, /async function cacheFirst\(request\)[\s\S]*caches\.match\(request\)/);
  assert.match(serviceWorker, /async function navigationWithBoundedNetwork\(networkPromise\)[\s\S]*Promise\.race/);
  assert.match(serviceWorker, /request\.method !== "GET"[\s\S]*url\.pathname\.startsWith\("\/api\/"\)/);
  assert.match(serviceWorker, /event\.respondWith\(cacheFirst\(request\)\)/);
  assert.doesNotMatch(serviceWorker, /event\.respondWith\(fetch\(request\)/);
  assert.match(app, /serviceWorker\.register\("\/sw\.js\?v=77", \{ updateViaCache: "none" \}\)/);
  assert.doesNotMatch(app, /registration\.update\(\)/);
});

test("complete self-study exposes one-step teaching, recovery, questions, and explicit continuation controls", () => {
  const app = read("app.js");
  const html = read("index.html");
  const css = read("styles.css");
  assert.match(html, /id="selfStudyNavItem"/);
  assert.match(html, /id="view-self-study"/);
  assert.match(html, /id="selfStudyAnswerForm"/);
  assert.match(html, /id="selfStudyQuestionForm"/);
  assert.match(app, /async function loadSelfStudy\(/);
  assert.match(app, /fetch\(`\/api\/self-study\$\{path\}`/);
  assert.match(app, /selfStudyRequest\("\/submit"/);
  assert.match(app, /selfStudyRequest\("\/continue"/);
  assert.match(app, /selfStudyRequest\(current\.status === "paused" \? "\/resume" : "\/pause"/);
  assert.match(app, /selfStudyRequest\("\/question"/);
  assert.match(app, /selfStudyAnswerForm"\)\.addEventListener\("keydown", event => \{[\s\S]*shouldSubmitOnEnter\(event\)[\s\S]*selfStudyAnswerForm"\)\.requestSubmit\(\)/);
  assert.match(app, /daily-english-self-study-/);
  assert.match(app, /"-draft", "-attempt", "-continue", "-question"/);
  assert.match(css, /@media \(max-width:\s*520px\)[\s\S]*\.self-study-stage-list/s);
});

test("self-study exposes slow speech and Enter continuation after a completed answer", () => {
  const app = read("app.js");
  const css = read("styles.css");
  assert.match(app, /const SPEECH_SLOW_RATE = 0\.5/);
  assert.match(app, /speechButtonHtml\(pronunciationText, "播放当前英文", \{ includeSlow: true/);
  assert.match(app, /data-speak-rate=\"\$\{SPEECH_SLOW_RATE\}\"/);
  assert.match(app, /function handleSelfStudyStepEnter\(event\)/);
  assert.match(app, /document\.addEventListener\("keydown", handleSelfStudyStepEnter\)/);
  assert.match(app, /step\.status === "completed" && questionTypes\.includes\(step\.type\)/);
  assert.match(css, /\.speech-controls\s*\{[^}]*display:\s*inline-flex/);
  assert.match(css, /\.speech-controls \.speak-slow-button/);
});

test("AI generation reports connection failures and offers an explicit retry instead of silently returning", () => {
  const app = read("app.js");
  const html = read("index.html");
  assert.match(html, /id="retryAiConnection"/);
  assert.match(app, /function aiOptionsFailureMessage\(error\)/);
  assert.match(app, /async function retryAiConnection\(\)/);
  assert.match(app, /当前设备已断网；实时 AI 生成需要联网/);
  assert.match(app, /AI 尚未配置，请先打开 AI 设置/);
  assert.match(app, /\$\("#retryAiConnection"\)\.addEventListener\("click", retryAiConnection\)/);
  assert.doesNotMatch(app, /if \(aiGenerationInProgress \|\| !aiOptions\.configured\) return;/);
});

test("offline travel mode is explicit, account-bound, FIFO replayed, and never caches private API responses", () => {
  const app = read("app.js");
  const html = read("index.html");
  const css = read("styles.css");
  const serviceWorker = read("sw.js");
  const server = read("server.js");
  assert.match(html, /id="prepareOfflinePack"/);
  assert.match(html, /id="deleteOfflinePack"/);
  assert.match(html, /id="offlinePackStatus"/);
  assert.match(html, /id="startNextOfflineAiBatch"/);
  assert.match(html, /offline-store\.js\?v=77/);
  assert.match(html, /offline-learning\.js\?v=77/);
  assert.match(html, /offline-ai\.js\?v=77/);
  assert.match(html, /offline-replay\.js\?v=77/);
  assert.match(app, /function enterPreparedOfflineSession\(\)/);
  assert.match(app, /offlineStore\.activeAccountId\(\) !== accountId/);
  assert.match(app, /async function replayOfflineOutbox\(\)/);
  assert.match(app, /OFFLINE_REPLAY\.replayOutbox/);
  assert.match(app, /offlineStore\.inspectPack\(accountId\)/);
  assert.match(app, /offlineSession \|\| offlineOutboxCount/);
  assert.match(app, /服务器暂时找不到原题组；本机题目、草稿和队列已保留/);
  assert.match(app, /离线包已过期，但已下载的原题和草稿仍可继续/);
  assert.match(app, /mergeOfflinePackRenewal/);
  assert.match(app, /当前账号离线包/);
  assert.match(app, /offlineSession \|\| !browserIsOnline\(\)/);
  assert.match(app, /startNextOfflineAiBatch/);
  assert.match(app, /正式复习待联网/);
  assert.match(app, /正式复习句子快照将在恢复联网后准备/);
  assert.match(app, /\["auth_required", "account_mismatch"\]\.includes\(error\.code\)/);
  assert.match(app, /offlineGradePending/);
  assert.match(app, /目前没有写入得分、错题或能力证据/);
  assert.match(server, /outbox: \{ mode: "client-fifo", formalEvidencePending: true \}/);
  assert.doesNotMatch(`${app}\n${server}`, /\/api\/offline\/replay/);
  assert.match(serviceWorker, /url\.pathname\.startsWith\("\/api\/"\)\) return/);
  assert.doesNotMatch(serviceWorker, /\/api\/state/);
  assert.match(serviceWorker, /offline-store\.js\?v=77/);
  assert.match(serviceWorker, /offline-replay\.js\?v=77/);
  assert.match(css, /@media \(max-width: 520px\)[\s\S]*\.self-study-mode-actions button:not\(\.offline-pack-delete\)/);
});

test("daily study plan offers six free-choice projects and records sixty minutes across web and learning-window work", () => {
  const html = read("index.html");
  const app = read("app.js");
  const serviceWorker = read("sw.js");
  assert.match(html, /id="studyTimerButton"/);
  assert.match(html, /id="studyTimeProgress"/);
  assert.match(html, /id="studyPlanSteps"/);
  assert.match(html, /aria-label="今日可自由选择的学习项目"/);
  assert.doesNotMatch(html, /<ol class="study-plan-steps"/);
  assert.match(html, /今日 60 分钟学习计划/);
  assert.match(html, /完成六项和 60 分钟后才算今日达标/);
  assert.match(app, /DAILY_STUDY_PLAN/);
  assert.match(app, /function studyStageDescription\(stage\)/);
  assert.match(app, /openCurrentStudyStage/);
  assert.match(app, /async function launchStudyStageContent\(stage, activeStage = false\)/);
  assert.match(app, /ensureGuidedReviewSession\(DAILY_TARGET\)/);
  assert.match(app, /await generateAiQuestions\(\)/);
  assert.match(app, /setView\("preview-practice"\)/);
  assert.match(app, /focusStudyStageContent/);
  assert.match(app, /guidedStageActive \? buildGuidedReviewBatch\(DAILY_TARGET\) : buildBatch\(\)/);
  assert.match(read("styles.css"), /\.is-study-stage-target/);
  assert.match(app, /allowBackground/);
  assert.match(app, /STUDY_TIME_IDLE_TIMEOUT_MS = 5 \* 60 \* 1000/);
  assert.match(app, /document\.hidden/);
  assert.match(app, /model\.studyTime/);
  assert.match(app, /六项可以自由选择/);
  assert.match(app, /data-lucide="clock-3"/);
  assert.doesNotMatch(app, /String\(stage\.index \+ 1\)/);
  assert.doesNotMatch(app, /按顺序完成/);
  assert.doesNotMatch(html, /按顺序学习/);
  assert.match(html, /study-time\.js\?v=77/);
  assert.match(serviceWorker, /study-time\.js\?v=77/);
});
