(() => {
  "use strict";

  const SOUND_AUDIO = Object.freeze({
    "v-i-long": ["audio/phonemes/v-close-front.ogg"],
    "v-i-short": ["audio/phonemes/v-near-close-front.ogg"],
    "v-e": ["audio/phonemes/v-open-mid-front.ogg"],
    "v-ae": ["audio/phonemes/v-near-open-front.ogg"],
    "v-a-back": ["audio/phonemes/v-open-back.ogg"],
    "v-aw": ["audio/phonemes/v-open-mid-back-rounded.ogg"],
    "v-u-short": ["audio/phonemes/v-near-close-back-rounded.ogg"],
    "v-u-long": ["audio/phonemes/v-close-back-rounded.ogg"],
    "v-caret": ["audio/phonemes/v-open-mid-back-unrounded.ogg"],
    "v-er-stressed": ["audio/phonemes/v-r-colored.ogg"],
    "v-schwa": ["audio/phonemes/v-mid-central.ogg"],
    "v-er-unstressed": ["audio/phonemes/v-mid-central.ogg", "audio/phonemes/c-r.ogg"],
    "v-ei": ["audio/phonemes/v-close-mid-front.ogg", "audio/phonemes/v-near-close-front.ogg"],
    "v-ai": ["audio/phonemes/v-open-front.ogg", "audio/phonemes/v-near-close-front.ogg"],
    "v-oi": ["audio/phonemes/v-open-mid-back-rounded.ogg", "audio/phonemes/v-near-close-front.ogg"],
    "v-ou": ["audio/phonemes/v-close-mid-back.ogg", "audio/phonemes/v-near-close-back-rounded.ogg"],
    "v-au": ["audio/phonemes/v-au.wav"],
    "v-ir": ["audio/phonemes/v-near-close-front.ogg", "audio/phonemes/c-r.ogg"],
    "v-air": ["audio/phonemes/v-ea.wav", "audio/phonemes/c-r.ogg"],
    "v-ur": ["audio/phonemes/v-ua.wav", "audio/phonemes/c-r.ogg"],
    "c-p": ["audio/phonemes/c-p.ogg"],
    "c-b": ["audio/phonemes/c-b.ogg"],
    "c-t": ["audio/phonemes/c-t.ogg"],
    "c-d": ["audio/phonemes/c-d.ogg"],
    "c-k": ["audio/phonemes/c-k.ogg"],
    "c-g": ["audio/phonemes/c-g.ogg"],
    "c-f": ["audio/phonemes/c-f.ogg"],
    "c-v": ["audio/phonemes/c-v.ogg"],
    "c-th-voiceless": ["audio/phonemes/c-th-voiceless.ogg"],
    "c-th-voiced": ["audio/phonemes/c-th-voiced.ogg"],
    "c-s": ["audio/phonemes/c-s.ogg"],
    "c-z": ["audio/phonemes/c-z.ogg"],
    "c-sh": ["audio/phonemes/c-sh.ogg"],
    "c-zh": ["audio/phonemes/c-zh.ogg"],
    "c-h": ["audio/phonemes/c-h.ogg"],
    "c-ch": ["audio/phonemes/c-ch.ogg"],
    "c-j": ["audio/phonemes/c-j.ogg"],
    "c-m": ["audio/phonemes/c-m.ogg"],
    "c-n": ["audio/phonemes/c-n.ogg"],
    "c-ng": ["audio/phonemes/c-ng.ogg"],
    "c-l": ["audio/phonemes/c-l.ogg"],
    "c-r": ["audio/phonemes/c-r.ogg"],
    "c-y": ["audio/phonemes/c-y.ogg"],
    "c-w": ["audio/phonemes/c-w.ogg"]
  });

  const pronunciationData = {
    version: 2,
    locale: "en-US",
    title: "英语基础发音参考表",
    summary: "以当前课程的美式发音为主，整理 20 个元音参考音和 24 个辅音，共 44 个基础音。先学课程标记为“已学”的音，其余内容只需随用随查，不要求一次背完。",
    audioNotice: "卡片顶部喇叭播放目标音素本身（组合音会按音素段播放）；示范词行的喇叭播放完整单词。辅音录音可能配极短元音，便于听清释放动作。",
    accentNotice: "不同词典和口音的写法会有差异，例如 /e/ 也常写成 /ɛ/，美式 hot 的 /ɑ/ 在英式中常写成 /ɒ/，美式 /oʊ/ 在英式中常写成 /əʊ/。这些通常是口音或标注体系差异，不代表其中一种一定错误。",
    concepts: [
      {
        id: "symbols",
        title: "字母和音标不是一回事",
        summary: "字母是拼写符号，音标记录实际声音。一个字母可能有不同读音，同一个音也可能由不同字母组合表示。",
        action: "看到 / / 中的符号时，把它当成“声音说明”，不要把音标按字母名称念。",
        example: "字母 a 在 cat 中发 /æ/，在 about 中可发 /ə/。"
      },
      {
        id: "vowels",
        title: "元音",
        summary: "发音时气流从口腔较顺畅地通过，主要靠嘴巴开合、舌头前后高低和嘴唇形状改变声音。元音通常是音节的中心。",
        action: "先摆好口型，再发声；重点感受舌位和嘴巴大小，不要急着用汉字完全代替。",
        example: "cat /kæt/ 中间的 /æ/ 是元音。"
      },
      {
        id: "consonants",
        title: "辅音",
        summary: "发音时嘴唇、牙齿或舌头会挡住、摩擦或改变气流。辅音通常和元音组合成单词。",
        action: "只做目标动作，不在后面偷偷加“啊、呃、衣”等元音。/t/ 是短促放开，不是完整的“特”。",
        example: "cat /kæt/ 两边的 /k/ 和 /t/ 是辅音。"
      },
      {
        id: "voicing",
        title: "清音和浊音",
        summary: "有些辅音动作相同，区别在于声带是否振动。清音主要送气，浊音同时让喉咙振动。",
        action: "把手轻放在喉咙上，连续发 /s/ 再发 /z/：/s/ 基本不振动，/z/ 能感觉到振动。",
        example: "/p/—/b/、/t/—/d/、/s/—/z/ 都是常见清浊音搭档。"
      },
      {
        id: "syllables",
        title: "音节和重音",
        summary: "一个音节通常有一个元音核心。多音节词里会有更响、更清楚的重读音节，音标中的 ˈ 放在重读音节前。",
        action: "先按元音核心把词分成小段，再把带 ˈ 的那一段读得更清楚；不要把每一段读得一样重。",
        example: "about /əˈbaʊt/ 有两个音节，重音在第二个音节。"
      }
    ],
    phonemes: [
      {
        id: "v-i-long",
        symbol: "/iː/",
        type: "vowel",
        subtype: "长元音",
        learned: false,
        example: "sheep",
        exampleZh: "绵羊",
        examplePhonetic: "/ʃiːp/",
        mouth: "嘴角稍向两边展开，舌头前部抬高，口腔开口很小。",
        action: "保持口型，声音比 /ɪ/ 更紧、更长，但不要在末尾加别的音。",
        chineseHint: "可先借“衣”的方向找声音，但嘴角更展开，且要稳定保持。",
        pitfall: "不要把 sheep 读成 ship；长短和口型都会影响词义。"
      },
      {
        id: "v-i-short",
        symbol: "/ɪ/",
        type: "vowel",
        subtype: "短元音",
        learned: true,
        example: "sit",
        exampleZh: "坐",
        examplePhonetic: "/sɪt/",
        mouth: "嘴唇放松并微微张开，舌头前部稍抬，但比 /iː/ 更低。",
        action: "声音短、轻、放松，立刻接下一个辅音。",
        chineseHint: "接近很短、很放松的“衣”，但不能拖长。",
        pitfall: "不要为了读清楚而变成长音 /iː/。"
      },
      {
        id: "v-e",
        symbol: "/e/",
        type: "vowel",
        subtype: "短元音",
        learned: true,
        example: "bed",
        exampleZh: "床",
        examplePhonetic: "/bed/",
        mouth: "嘴巴微微张开，舌头前部处于中等高度，开口比 /æ/ 小。",
        action: "保持一个短促的单音，发完立即收住，不向 /ɪ/ 滑动。",
        chineseHint: "接近“诶”的开头，但只取最前面的一小段，不拖成“诶—”。",
        pitfall: "很多美式词典把这个音写成 /ɛ/；不要把符号差异当成两个必须分开的新音。"
      },
      {
        id: "v-ae",
        symbol: "/æ/",
        type: "vowel",
        subtype: "短元音",
        learned: true,
        example: "cat",
        exampleZh: "猫",
        examplePhonetic: "/kæt/",
        mouth: "下巴放低，嘴巴张得较大，嘴角略向两边，舌头前部放低。",
        action: "用较扁、较亮的声音短促发出，口型保持不滑动。",
        chineseHint: "像“哎”的最前面，但嘴张得更大、更扁，只发一个短音。",
        pitfall: "不要读成 /e/；cat 的嘴巴要比 bed 张得更大。"
      },
      {
        id: "v-a-back",
        symbol: "/ɑ/",
        type: "vowel",
        subtype: "短元音",
        learned: true,
        example: "hot",
        exampleZh: "热的",
        examplePhonetic: "/hɑt/",
        mouth: "下巴放低，嘴巴自然张开，舌头放低并稍向后，嘴唇不要刻意变圆。",
        action: "从喉咙和口腔后部发出短促、开放的声音。",
        chineseHint: "方向接近张嘴说“啊”，但位置更靠后，而且要短。",
        pitfall: "英式词典中的 hot 常标 /ɒ/；网页示范词采用美式朗读。"
      },
      {
        id: "v-aw",
        symbol: "/ɔ/",
        type: "vowel",
        subtype: "后元音",
        learned: false,
        example: "law",
        exampleZh: "法律",
        examplePhonetic: "/lɔ/",
        mouth: "嘴唇略微收圆，舌头后部抬起，嘴巴保持中等开度。",
        action: "稳定发一个靠后的圆唇音，不要先加 /w/。",
        chineseHint: "可借“哦”的方向找声音，但开口更稳定，不读成“窝”。",
        pitfall: "部分美式口音会把 /ɔ/ 和 /ɑ/ 合并；英式词典也常写作 /ɔː/。"
      },
      {
        id: "v-u-short",
        symbol: "/ʊ/",
        type: "vowel",
        subtype: "短元音",
        learned: false,
        example: "book",
        exampleZh: "书",
        examplePhonetic: "/bʊk/",
        mouth: "嘴唇轻微收圆但保持放松，舌头后部抬起，位置比 /uː/ 略低。",
        action: "声音很短，嘴唇不要向前撅得过紧。",
        chineseHint: "接近很短、很松的“乌”，发到一半就收住。",
        pitfall: "不要把 book 读成带长音 /uː/ 的 boot。"
      },
      {
        id: "v-u-long",
        symbol: "/uː/",
        type: "vowel",
        subtype: "长元音",
        learned: false,
        example: "food",
        exampleZh: "食物",
        examplePhonetic: "/fuːd/",
        mouth: "嘴唇收圆并稍向前，舌头后部抬高，口腔开口较小。",
        action: "保持圆唇口型，把声音平稳延长一点。",
        chineseHint: "接近拉长的“乌”，但不要在开头加一个明显的 /w/。",
        pitfall: "不要读成两个音，也不要在末尾加“呃”。"
      },
      {
        id: "v-caret",
        symbol: "/ʌ/",
        type: "vowel",
        subtype: "短元音",
        learned: false,
        example: "cup",
        exampleZh: "杯子",
        examplePhonetic: "/kʌp/",
        mouth: "嘴唇自然放松，嘴巴中等张开，舌头放在口腔中部并稍低。",
        action: "不用刻意圆唇或咧嘴，短促地从中间位置发声。",
        chineseHint: "介于短“啊”和轻“饿”之间，只能借方向，汉语里没有完全相同的音。",
        pitfall: "不要把 cup 读成 cop；嘴唇不要收圆。"
      },
      {
        id: "v-er-stressed",
        symbol: "/ɝ/",
        type: "vowel",
        subtype: "卷舌元音",
        learned: false,
        example: "bird",
        exampleZh: "鸟",
        examplePhonetic: "/bɝd/",
        mouth: "嘴唇自然，舌尖可微抬但不碰上颚，或把舌身中部拱起形成美式 r 色。",
        action: "元音和 r 色一次完成，声音较重且清楚。",
        chineseHint: "可借“儿”的方向找卷舌感，但不要先发元音再单独补一个 r。",
        pitfall: "英式非卷舌词典常用 /ɜː/ 标记对应部分。"
      },
      {
        id: "v-schwa",
        symbol: "/ə/",
        type: "vowel",
        subtype: "弱读元音",
        learned: false,
        example: "about",
        exampleZh: "关于",
        examplePhonetic: "/əˈbaʊt/",
        mouth: "嘴唇和舌头都尽量放松，口腔中央留一个小开口。",
        action: "轻、短、弱地带过，不要把它读成清楚响亮的完整汉字音。",
        chineseHint: "接近非常轻短的“呃”，几乎一带而过。",
        pitfall: "它常出现在非重读音节；读得太重会让英语节奏不自然。"
      },
      {
        id: "v-er-unstressed",
        symbol: "/ɚ/",
        type: "vowel",
        subtype: "卷舌弱元音",
        learned: false,
        example: "teacher",
        exampleZh: "老师",
        examplePhonetic: "/ˈtiːtʃɚ/",
        mouth: "口腔保持放松，同时把舌头摆成轻微的美式 r 口型。",
        action: "轻而短地发出带 r 色的弱音，不要抢过前面重读音节。",
        chineseHint: "像很轻的“儿”，但必须弱读，不能单独拖长。",
        pitfall: "英式非卷舌读音末尾常只标 /ə/，不会明显读出 r。"
      },
      {
        id: "v-ei",
        symbol: "/eɪ/",
        type: "vowel",
        subtype: "双元音",
        learned: false,
        example: "day",
        exampleZh: "白天",
        examplePhonetic: "/deɪ/",
        mouth: "从较开放的前元音口型开始，舌头稍向上移动，嘴巴逐渐变小。",
        action: "在同一个音节里从 /e/ 平滑滑向 /ɪ/，重心放在开头。",
        chineseHint: "接近汉语“诶”的滑动方向，但要保持一个连贯音节。",
        pitfall: "不要拆成两个独立音，也不要在中间停顿。"
      },
      {
        id: "v-ai",
        symbol: "/aɪ/",
        type: "vowel",
        subtype: "双元音",
        learned: false,
        example: "my",
        exampleZh: "我的",
        examplePhonetic: "/maɪ/",
        mouth: "从嘴巴较大的开放位置开始，舌头向前上方移动，嘴巴逐渐收小。",
        action: "从开放的 /a/ 平滑滑向 /ɪ/，只占一个音节。",
        chineseHint: "接近“爱”的滑动方向；开头要张嘴，结尾迅速收小。",
        pitfall: "不要读成平直的单元音，也不要分成“啊—衣”两个音节。"
      },
      {
        id: "v-oi",
        symbol: "/ɔɪ/",
        type: "vowel",
        subtype: "双元音",
        learned: false,
        example: "boy",
        exampleZh: "男孩",
        examplePhonetic: "/bɔɪ/",
        mouth: "从圆唇、靠后的 /ɔ/ 开始，舌头向前上方移动，嘴唇逐渐展开。",
        action: "把两个位置连成一次平滑滑动，开头较响，结尾较轻。",
        chineseHint: "可借“奥衣”快速连读的方向，但必须合成一个音节。",
        pitfall: "不要在两个部分之间停顿或额外加辅音。"
      },
      {
        id: "v-ou",
        symbol: "/oʊ/",
        type: "vowel",
        subtype: "双元音",
        learned: false,
        example: "go",
        exampleZh: "去",
        examplePhonetic: "/ɡoʊ/",
        mouth: "从中等开口开始，舌头向后上方移动，嘴唇逐渐收圆。",
        action: "让声音自然滑向 /ʊ/，不要从一开始就把嘴撅得很紧。",
        chineseHint: "接近“欧”的滑动方向，前半段更清楚，后半段轻轻收圆。",
        pitfall: "英式词典常写作 /əʊ/；这是常见标注差异。"
      },
      {
        id: "v-au",
        symbol: "/aʊ/",
        type: "vowel",
        subtype: "双元音",
        learned: false,
        example: "now",
        exampleZh: "现在",
        examplePhonetic: "/naʊ/",
        mouth: "从张开的低舌位开始，舌头向后上方移动，嘴唇逐渐收圆。",
        action: "开头响亮开放，随后快速滑到轻短的 /ʊ/。",
        chineseHint: "接近“奥”的滑动方向，但起点更张开，结尾明显收圆。",
        pitfall: "不要只发平直的“奥”，要让口型真正发生移动。"
      },
      {
        id: "v-ir",
        symbol: "/ɪr/",
        type: "vowel",
        subtype: "元音加 r",
        learned: false,
        example: "near",
        exampleZh: "附近的",
        examplePhonetic: "/nɪr/",
        mouth: "先用放松的 /ɪ/ 口型，再把舌头收向美式 r 位置，舌尖不要碰上颚。",
        action: "在一个音节里连续完成 /ɪ/ 到 r 色的变化。",
        chineseHint: "可借“衣尔”快速相连的方向，但不能读成两个汉语音节。",
        pitfall: "英式非卷舌词典常写成 /ɪə/。"
      },
      {
        id: "v-air",
        symbol: "/er/",
        type: "vowel",
        subtype: "元音加 r",
        learned: false,
        example: "hair",
        exampleZh: "头发",
        examplePhonetic: "/her/",
        mouth: "从 /e/ 附近的中等开口开始，再把舌头收向美式 r 位置。",
        action: "保持一个音节，前面的元音清楚，随后自然带出 r 色。",
        chineseHint: "方向有点像快速说“艾尔”，但中间不能断开。",
        pitfall: "英式非卷舌词典常写成 /eə/；部分美式词典也写 /ɛr/。"
      },
      {
        id: "v-ur",
        symbol: "/ʊr/",
        type: "vowel",
        subtype: "元音加 r",
        learned: false,
        example: "tour",
        exampleZh: "旅行",
        examplePhonetic: "/tʊr/",
        mouth: "先轻微圆唇发 /ʊ/，再把舌头收向美式 r 位置。",
        action: "两个位置连续完成，不要在中间增加新的音节。",
        chineseHint: "可借“乌尔”快速连读的方向，但开头要短而松。",
        pitfall: "这个词的口音差异很大；英式词典常见 /ʊə/，部分美式口音会读成 /tʊr/ 或 /tɔr/。"
      },
      {
        id: "c-p",
        symbol: "/p/",
        type: "consonant",
        subtype: "爆破清音",
        learned: false,
        example: "pen",
        exampleZh: "笔",
        examplePhonetic: "/pen/",
        mouth: "双唇先完全闭合，再突然打开。",
        action: "只用气流做短促爆破，喉咙不振动；词首通常能感到一小股气。",
        chineseHint: "像“泼”的最前面，但立刻停住，绝不能带出后面的“哦”。",
        pitfall: "拿纸放在嘴前练习，词首 /p/ 的气流应能让纸轻动。"
      },
      {
        id: "c-b",
        symbol: "/b/",
        type: "consonant",
        subtype: "爆破浊音",
        learned: false,
        example: "big",
        exampleZh: "大的",
        examplePhonetic: "/bɪɡ/",
        mouth: "双唇先完全闭合，再短促打开，动作和 /p/ 相近。",
        action: "打开时声带振动，送气比词首 /p/ 弱。",
        chineseHint: "像“波”的最前面，但不要把“哦”读出来。",
        pitfall: "用手摸喉咙对比 /p/ 和 /b/，/b/ 应有振动。"
      },
      {
        id: "c-t",
        symbol: "/t/",
        type: "consonant",
        subtype: "爆破清音",
        learned: false,
        example: "top",
        exampleZh: "顶部",
        examplePhonetic: "/tɑp/",
        mouth: "舌尖贴住上牙后方的齿龈，挡住气流后迅速放开。",
        action: "喉咙不振动，词首通常有短促送气。",
        chineseHint: "像“特”的最前面，只做舌尖放开的动作，不要读出“饿”。",
        pitfall: "单独练 /t/ 时不要把它读成完整的汉字“特”。"
      },
      {
        id: "c-d",
        symbol: "/d/",
        type: "consonant",
        subtype: "爆破浊音",
        learned: false,
        example: "dog",
        exampleZh: "狗",
        examplePhonetic: "/dɔɡ/",
        mouth: "舌尖贴住上牙后方的齿龈，再短促放开。",
        action: "动作和 /t/ 相近，但发音时声带振动，送气较弱。",
        chineseHint: "像“的”的最前面，但不要带出后面的元音。",
        pitfall: "不要在单词末尾的 /d/ 后面补一个“呃”。"
      },
      {
        id: "c-k",
        symbol: "/k/",
        type: "consonant",
        subtype: "爆破清音",
        learned: false,
        example: "cat",
        exampleZh: "猫",
        examplePhonetic: "/kæt/",
        mouth: "舌头后部抬起贴住软腭，挡住气流后迅速放开。",
        action: "喉咙不振动，词首会有一小股气从口中释放。",
        chineseHint: "像“克”的最前面，只保留爆破动作，不读出“呃”。",
        pitfall: "字母 c 在 cat 中发 /k/，但发音和拼写不是一一固定对应。"
      },
      {
        id: "c-g",
        symbol: "/ɡ/",
        type: "consonant",
        subtype: "爆破浊音",
        learned: false,
        example: "pig",
        exampleZh: "猪",
        examplePhonetic: "/pɪɡ/",
        mouth: "舌头后部抬起贴住软腭，再短促放开，位置和 /k/ 相同。",
        action: "放开时声带振动，送气比 /k/ 弱。",
        chineseHint: "像“哥”的最前面，但结尾不能再加一个“哥”或“呃”。",
        pitfall: "读 pig 时要用 /ɡ/ 收尾，不要把结尾拖成一个新音节。"
      },
      {
        id: "c-f",
        symbol: "/f/",
        type: "consonant",
        subtype: "摩擦清音",
        learned: false,
        example: "fish",
        exampleZh: "鱼",
        examplePhonetic: "/fɪʃ/",
        mouth: "上门牙轻触下唇内侧，留出窄缝。",
        action: "让气流持续从缝中摩擦出来，喉咙不振动。",
        chineseHint: "像“夫”的最前面并可以持续吹气，但不要带出“乌”。",
        pitfall: "不要把上下嘴唇都闭起来；那会变成 /p/。"
      },
      {
        id: "c-v",
        symbol: "/v/",
        type: "consonant",
        subtype: "摩擦浊音",
        learned: false,
        example: "van",
        exampleZh: "货车",
        examplePhonetic: "/væn/",
        mouth: "上门牙轻触下唇内侧，位置和 /f/ 相同。",
        action: "让气流持续摩擦，同时让声带振动。",
        chineseHint: "汉语普通话没有完全相同的音；先持续发 /f/，再打开喉咙振动。",
        pitfall: "不要把 /v/ 读成 /w/；/v/ 必须有牙齿和下唇摩擦。"
      },
      {
        id: "c-th-voiceless",
        symbol: "/θ/",
        type: "consonant",
        subtype: "摩擦清音",
        learned: false,
        example: "thin",
        exampleZh: "瘦的",
        examplePhonetic: "/θɪn/",
        mouth: "舌尖轻放在上下门牙之间，或轻触上门牙背面。",
        action: "从舌尖周围持续吹气，喉咙不振动。",
        chineseHint: "汉语没有对应音；可以记成“轻咬舌头吹气”，不是“丝”。",
        pitfall: "不要缩回舌头读成 /s/，也不要完全咬住让气流出不来。"
      },
      {
        id: "c-th-voiced",
        symbol: "/ð/",
        type: "consonant",
        subtype: "摩擦浊音",
        learned: false,
        example: "this",
        exampleZh: "这个",
        examplePhonetic: "/ðɪs/",
        mouth: "舌尖轻放在上下门牙之间，位置和 /θ/ 相同。",
        action: "保持轻微摩擦，同时让声带振动。",
        chineseHint: "先摆出“咬舌”口型，再带着喉咙振动；汉语没有完全相同的音。",
        pitfall: "不要替换成 /d/ 或 /z/；舌尖必须能在牙齿处看到或感觉到。"
      },
      {
        id: "c-s",
        symbol: "/s/",
        type: "consonant",
        subtype: "摩擦清音",
        learned: false,
        example: "sat",
        exampleZh: "坐了",
        examplePhonetic: "/sæt/",
        mouth: "牙齿靠近，舌尖接近但不碰上牙后方，让中间留一条窄缝。",
        action: "气流从舌头中间持续摩擦，喉咙不振动。",
        chineseHint: "像“丝”的最前面，可以持续发，但不要带出“衣”。",
        pitfall: "只保留嘶嘶气流；单独的 /s/ 不是汉字“丝”。"
      },
      {
        id: "c-z",
        symbol: "/z/",
        type: "consonant",
        subtype: "摩擦浊音",
        learned: false,
        example: "zoo",
        exampleZh: "动物园",
        examplePhonetic: "/zuː/",
        mouth: "牙齿和舌头位置与 /s/ 相近，中间保留窄缝。",
        action: "持续摩擦并让声带振动。",
        chineseHint: "先持续发 /s/，保持口型不动，再让喉咙加入振动。",
        pitfall: "is /ɪz/ 的最后一个音是 /z/，不是清音 /s/。"
      },
      {
        id: "c-sh",
        symbol: "/ʃ/",
        type: "consonant",
        subtype: "摩擦清音",
        learned: false,
        example: "shop",
        exampleZh: "商店",
        examplePhonetic: "/ʃɑp/",
        mouth: "舌头比 /s/ 稍向后，舌面接近上颚，嘴唇略微收圆。",
        action: "让较宽的气流持续摩擦，喉咙不振动。",
        chineseHint: "像提醒安静时“嘘”的最前面，但不要把后面的 ü 音带出来。",
        pitfall: "sh 两个字母在 shop 中合起来表示一个 /ʃ/。"
      },
      {
        id: "c-zh",
        symbol: "/ʒ/",
        type: "consonant",
        subtype: "摩擦浊音",
        learned: false,
        example: "vision",
        exampleZh: "视力；景象",
        examplePhonetic: "/ˈvɪʒən/",
        mouth: "舌头和嘴唇位置与 /ʃ/ 相近。",
        action: "保持摩擦，同时让声带持续振动。",
        chineseHint: "先发 /ʃ/ 的气流，再保持口型加入喉咙振动；汉语没有完全对应音。",
        pitfall: "它不是 /dʒ/；/ʒ/ 可以连续延长，没有先堵住再爆开的动作。"
      },
      {
        id: "c-h",
        symbol: "/h/",
        type: "consonant",
        subtype: "摩擦清音",
        learned: false,
        example: "hot",
        exampleZh: "热的",
        examplePhonetic: "/hɑt/",
        mouth: "喉咙和口腔保持打开，嘴巴提前准备好后面元音的口型。",
        action: "像轻轻哈气一样让气流通过，声带不主动振动。",
        chineseHint: "像“喝”的最前面那口气，但不要把“饿”读出来。",
        pitfall: "不要用力摩擦喉咙；/h/ 是轻柔气流。"
      },
      {
        id: "c-ch",
        symbol: "/tʃ/",
        type: "consonant",
        subtype: "破擦清音",
        learned: false,
        example: "chair",
        exampleZh: "椅子",
        examplePhonetic: "/tʃer/",
        mouth: "舌尖或舌面前部先挡住气流，再在较靠后的窄缝中放开摩擦。",
        action: "堵住和摩擦紧密连在一起，喉咙不振动，只算一个辅音。",
        chineseHint: "像“吃”的最前面，但不要带出后面的元音。",
        pitfall: "不要拆成慢慢分开的 /t/ 和 /ʃ/。"
      },
      {
        id: "c-j",
        symbol: "/dʒ/",
        type: "consonant",
        subtype: "破擦浊音",
        learned: false,
        example: "jam",
        exampleZh: "果酱",
        examplePhonetic: "/dʒæm/",
        mouth: "口腔动作与 /tʃ/ 相近，先挡住气流，再放开摩擦。",
        action: "整个动作中加入声带振动，只算一个辅音。",
        chineseHint: "像“知”或“这”的最前面，但不要带出后面的元音。",
        pitfall: "不要把字母 j 的名称 /dʒeɪ/ 当成单独的辅音 /dʒ/。"
      },
      {
        id: "c-m",
        symbol: "/m/",
        type: "consonant",
        subtype: "鼻音",
        learned: false,
        example: "man",
        exampleZh: "男人",
        examplePhonetic: "/mæn/",
        mouth: "双唇完全闭合，舌头放松。",
        action: "让声带振动，气流从鼻腔出来；可以连续保持。",
        chineseHint: "像“摸”的最前面，只保留闭嘴的鼻音，不要读出“哦”。",
        pitfall: "捏住鼻子时 /m/ 会发不顺，这能帮助确认鼻腔气流。"
      },
      {
        id: "c-n",
        symbol: "/n/",
        type: "consonant",
        subtype: "鼻音",
        learned: false,
        example: "pen",
        exampleZh: "笔",
        examplePhonetic: "/pen/",
        mouth: "舌尖贴住上牙后方的齿龈，嘴唇自然。",
        action: "让声带振动，气流从鼻腔出来。",
        chineseHint: "像“呢”的最前面，只保留舌尖顶住的鼻音，不读出“饿”。",
        pitfall: "不要把单独的 /n/ 读成完整汉字“恩”。"
      },
      {
        id: "c-ng",
        symbol: "/ŋ/",
        type: "consonant",
        subtype: "鼻音",
        learned: false,
        example: "sing",
        exampleZh: "唱歌",
        examplePhonetic: "/sɪŋ/",
        mouth: "舌头后部抬起贴住软腭，舌尖放松，不碰上牙后方。",
        action: "声带振动，气流从鼻腔出来。",
        chineseHint: "接近汉语“英”末尾的 ng，只取最后的鼻音部分。",
        pitfall: "sing 的结尾通常只有 /ŋ/，不要自动再补一个 /ɡ/。"
      },
      {
        id: "c-l",
        symbol: "/l/",
        type: "consonant",
        subtype: "边音",
        learned: false,
        example: "leg",
        exampleZh: "腿",
        examplePhonetic: "/leɡ/",
        mouth: "舌尖贴住上牙后方的齿龈，两侧留出气流通道。",
        action: "声带振动，让气流从舌头两侧通过。",
        chineseHint: "像“了”的最前面，但只保留舌尖动作，不要读出“饿”。",
        pitfall: "词尾 l 的舌位可能更靠后，但初学先把词首清晰的 /l/ 做对。"
      },
      {
        id: "c-r",
        symbol: "/r/",
        type: "consonant",
        subtype: "近音",
        learned: false,
        example: "red",
        exampleZh: "红色的",
        examplePhonetic: "/red/",
        mouth: "舌尖微抬并向后收，或把舌身中部拱起，但舌头不要碰到上颚；嘴唇可略圆。",
        action: "声带振动，让气流从舌头中央顺畅通过。",
        chineseHint: "汉语普通话没有完全相同的美式 /r/；关键是舌头悬空、不弹舌。",
        pitfall: "不要读成汉语拼音 r，也不要把舌尖弹到上颚变成颤音。"
      },
      {
        id: "c-y",
        symbol: "/j/",
        type: "consonant",
        subtype: "近音",
        learned: false,
        example: "yes",
        exampleZh: "是的",
        examplePhonetic: "/jes/",
        mouth: "舌头前部抬高接近硬腭，嘴唇自然展开。",
        action: "从接近 /i/ 的位置迅速滑向后面的元音，声带振动。",
        chineseHint: "像“耶”的最前面滑音，只取开头，不读成完整的“耶”。",
        pitfall: "音标 /j/ 通常对应字母 y 的发音，不是英文字母 j 的名称。"
      },
      {
        id: "c-w",
        symbol: "/w/",
        type: "consonant",
        subtype: "近音",
        learned: false,
        example: "wet",
        exampleZh: "湿的",
        examplePhonetic: "/wet/",
        mouth: "嘴唇先明显收圆，舌头后部抬高，然后迅速打开进入后面的元音。",
        action: "声带振动，圆唇动作很短，不单独形成一个音节。",
        chineseHint: "像“我”或“乌”的最前面滑动，但不能读出完整元音。",
        pitfall: "不要和 /v/ 混淆；/w/ 不用上牙接触下唇。"
      }
    ]
  };

  pronunciationData.phonemes = pronunciationData.phonemes.map(item => ({ ...item, soundAudio: SOUND_AUDIO[item.id] || [] }));
  pronunciationData.audioCredits = "音素录音来自 Wikimedia Commons，具体作者与许可请查看音频来源页。";
  window.ENGLISH_PRONUNCIATION_DATA = pronunciationData;
})();
